name: Wrapper for Azure/static-web-apps-deploy
description: Wrapper for Azure/static-web-apps-deploy so build of action is not called if action is skipped

inputs:
  azure_static_web_apps_api_token:
    required: true
    description: 'Azure Static Web Apps API token'
  action:
    required: true
    description: 'Action command'
  repo_token:
    required: false
    description: 'Repo token'
  app_location:
    required: false
    description: 'App source code path'
  api_location:
    required: false
    description: 'Api source code path'
  output_location:
    required: false
    description: 'Built app content directory'
  deployment_environment:
    description: 'Name of the Azure Static Web Apps environment to deploy to.'
    required: false
  skip_api_build:
    description: 'Skip API build'
    required: false
    default: 'false'
  skip_app_build:
    description: 'Skip app build'
    required: false
    default: 'false'
outputs:
  static_web_app_url:
    description: 'The URL of the deployed static web app'
    value: ${{ steps.build-deploy.outputs.static_web_app_url }}

runs:
  using: 'composite'
  steps:
    - uses: Azure/static-web-apps-deploy@v1
      id: build-deploy
      with:
        azure_static_web_apps_api_token: ${{ inputs.azure_static_web_apps_api_token }}
        repo_token: ${{ inputs.repo_token }}
        action: ${{ inputs.action }}
        app_location: ${{ inputs.app_location }}
        api_location: ${{ inputs.api_location }}
        output_location: ${{ inputs.output_location }}
        verbose: true
        deployment_environment: ${{ inputs.deployment_environment }}
        skip_api_build: ${{ inputs.skip_api_build }}
        skip_app_build: ${{ inputs.skip_app_build }}

    # Bloody azure swa deployment changes the permissions of the app directory
    # Reset the permissions to the original user
    - run: |
        sudo chown -R $USER:$USER .
        sudo chmod -R 755 .
      shell: bash
      working-directory: ${{ inputs.app_location }}
