name: CI-SWA-PR-CLOSE

on:
  pull_request:
    types:
      - closed

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: write # to create comments (actions/github-script)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}

  close-azure:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check if AZURE_STATIC_WEB_APPS_API_TOKEN is set
      - id: do-swa-azure
        if: ${{ steps.main-push.outputs.result == 'true' || steps.pr-to-main.outputs.result == 'true' }}
        run: |
          if [[ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]]; then
            echo "Deploy token not set. Skipping deployment."
            echo "result=false" >> "$GITHUB_OUTPUT"
          else
            echo "Deploy token is set. Proceeding with deployment."
            echo "result=true" >> "$GITHUB_OUTPUT"
          fi
        working-directory: .

      - id: app-token
        uses: kt-public/github-actions/create-github-app-token@v1
        if: ${{ steps.do-swa-azure.outputs.result == 'true' }}
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
          configure-git: false

      - uses: ./.github/actions/static-web-apps-deploy-wrapper
        if: ${{ steps.do-swa-azure.outputs.result == 'true' }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ steps.app-token.outputs.token }} # Used for Github integrations (i.e. PR comments)
          action: 'close'

  retry-failed:
    runs-on: ubuntu-latest
    needs: [close-azure]
    if: failure() && fromJSON(github.run_attempt) < 3
    permissions:
      actions: write
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run ci-retry.yml -F run_id=${{ github.run_id }} -F concurrency=${{ github.workflow }}-${{ github.event.number || github.ref_name }}
