name: CI-SWA

on:
  workflow_call:
    inputs:
      # pass the matrix node version to the called workflow
      matrix-node-version:
        required: true
        type: string
      cache-additional-path:
        required: false
        type: string
      cache-reset:
        required: false
        type: boolean
    secrets:
      WORKFLOW_APP_ID:
      WORKFLOW_APP_PRIVATE_KEY:
      AZURE_STATIC_WEB_APPS_API_TOKEN:

permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: write # to create comments (actions/github-script)
  actions: write # to create a comment (actions/github-script)

jobs:
