name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  # we call `pnpm playwright install` instead
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to create a comment (actions/github-script)
  pull-requests: write # to create comments (actions/github-script)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  ci:
    uses: kt-workflows/npm-ci/.github/workflows/main.yml@v1
    with:
      # pass the matrix node version to the called workflow
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
      cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
      # cache-reset: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
