name: CI

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  # group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  actions: write # to create a comment (actions/github-script)
  pull-requests: write # to create comments (actions/github-script)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}

  ci:
    uses: kt-workflows/npm-ci/.github/workflows/main.yml@v1
    with:
      # pass the matrix node version to the called workflow
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
      cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
      # cache-reset: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci-swa:
    uses: ./.github/workflows/ci-swa.yml
    with:
      # pass the matrix node version to the called workflow
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
      cache-additional-path: ${{ vars.CACHE_ADDITIONAL_PATH }}
      # cache-reset: true
    secrets:
      inherit
      # AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      # WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      # WORKFLOW_APP_PRIVATE_KEY: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}

  retry-failed:
    runs-on: ubuntu-latest
    needs: [ci, ci-swa]
    if: failure() && fromJSON(github.run_attempt) < 3
    permissions:
      actions: write
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run ci-retry.yml -F run_id=${{ github.run_id }} -F concurrency=${{ github.workflow }}-${{ github.event.number || github.ref_name }}
